# default layouts
layouts:
  default:
    apps:
      - name: sh
  ssh:
    apps:
      - name: ssh
        default: true
        commands:
          - command: exec ssh "{{name}}"
      - name: sshfs
        rules:
          - inPath("sshfs") && contains(TAGS, "sftp")
        commands:
          - command: mkdir -p "~/mnt/ssh/{{name}}"
          - command: sshfs -o default_permissions,idmap=user,noatime,follow_symlinks,_netdev,reconnect {{name}}:/ ~/mnt/ssh/{{name}}
  project:
    apps:
      - name: sh
        default: true
      - name: nvim
        rules:
          - inPath("nvim")
        commands:
          - command: nvim +'Telescope find_files hidden=false layout_config={height=0.9}'
        group: editor
      - name: git
        rules:
          - inPath("lazygit")
        commands:
          - command: lazygit
  kubernetes:
    apps:
      - name: kubectl
        default: true
        commands:
          - command: export KUBECONFIG="{{kubeConfig}}"
          - command: kubectl config set-context --current --namespace="{{namespace}}"
          - command: exec bash
      - name: k9s
        rules:
          - inPath("k9s")
        commands:
          - command: exec k9s --logoless --headless --readonly --kubeconfig "{{kubeConfig}}" --namespace "{{namespace}}"
  usql:
    apps:
      - name: usql
        default: true
        rules:
          - inPath("usql")
        commands:
          - command: exec usql {{name}}
  ldap:
    apps:
      - name: ldap
        default: true
        commands:
          - command: ldapsearch -H {{ldapHost}} -D {{ldapBindDN}} -w "{{ldapBindPassword}}" -b "{{id}}"
          - command: exec bash
  jira:
    apps:
      - name: jira-cli
        default: true
        rules:
          - inPath("jira")
        commands:
          - command: exec jira issue view {{name}}
  rundeck:
    apps:
      - name: rundeck-cli
        default: true
        rules:
          - inPath("rd")
        commands:
          - command: export RD_URL={{rundeckHost}}
          - command: export RD_TOKEN={{rundeckToken}}
          - command: exec bash
